services:
  mysql:
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d  # Optional: to import .sql file

  redis:
    ports:
      - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"
  
  zookeeper:
    container_name: zookeeper
    ports:
      - "127.0.0.1:${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    ports:
      - "127.0.0.1:${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
  edgemonitor_backend:
    image: bejoyjose/edgemonitor-backend:${IMAGE_TAG}
    hostname: backend
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      # - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      # - AWS_REGION=${AWS_REGION}
      # - BUCKET_NAME=${BUCKET_NAME}
      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  edgemonitor_dashboard:
    image: bejoyjose/edgemonitor-dashboard:${IMAGE_TAG}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}

  edgemonitor_gateway:
    image: bejoyjose/edgemonitor-gateway:${IMAGE_TAG}
    environment:
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
      - GATEWAY_SERVICE_URI=${GATEWAY_SERVICE_URI}
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"

  edgemonitor_notification:
    image: bejoyjose/edgemonitor-notification:${IMAGE_TAG}
    ports:
      - "${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"
    environment:
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - SPRING_PROFILES_ACTIVE=docker
        - NOTIFICATION_PORT=${NOTIFICATION_PORT}
        - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}      

